[sources.load_salesforce_marketing_cloud]
subdomain = "<my SFMC subdomain>"
client_id  = "<SFMC client_id>"
client_secret = "<SFMC client_secret>"

[destination.snowflake.credentials]
database = "RAW"
username = "DLT"
private_key = """-----BEGIN ENCRYPTED PRIVATE KEY-----
MI...Fj
-----END ENCRYPTED PRIVATE KEY-----"""
private_key_passphrase="<m< passphrase>"
host = "<my Snowflake account identified>"
warehouse = "WH_DLT"
role = "SYSADMIN"
